title: Riya Farhin
description: Data-driven healthcare professional with expertise in data analysis, database management, and data visualization. Skilled in SQL, Python, Power BI, Tableau, and Excel for creating analytics models, generating strategic business insights, and developing performance dashboards.
show_downloads: true
theme: jekyll-theme-minimal
